---
#NOTE: This assumes that the database is already configured!
- hosts: all
  vars:
    http_port: 80
  remote_user: ubuntu
  # become: True
  vars_files:
    - vars.yml
  tasks:
  # Ignoring errors because gunicorn could be down or not isntalled and it will fail as it should
  - name: Kill gunicorn processes if available 
    command: killall gunicorn
    ignore_errors: yes
    sudo: True

  # - name: Install application 
  #   pip:
  #     name: YTReviewsAPI
  #     virtualenv: /home/ubuntu/venv
  #     virtualenv_python: python3.5

  - name: Creating deployment directory
    file:
      path: /home/ubuntu/deployment
      state: directory
      owner: ubuntu

  - name: Moving requirements.txt for application 
    copy: 
      src: requirements.txt
      dest: /home/ubuntu/deployment/requirements.txt

  - name: Install requirements
    pip: 
      name: /home/ubuntu/deployment/requirements.txt
      extra_args: -r
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5

  - name: Copying static files
    copy:
      src: "{{ local_static_path }}"
      dest: /home/ubuntu/deployment/static
      directory_mode: True
      owner: ubuntu
      group: ubuntu
    sudo: True

  - name: Copying NginX Configuration
    template:
      src: templates/nginx.j2
      dest: /etc/nginx/sites-enabled/YTReviewsAPI
    sudo: True

  - name: Restart NginX
    service:
      name: nginx
      state: restarted
    sudo: True

  - name: Start application
    gunicorn:
      app: 'YTReviewsAPI'












