---
#NOTE: This assumes that the database is already configured!
- hosts: all
  vars:
    http_port: 80
  remote_user: ubuntu
  # become: True
  vars_files:
    - vars.yml
  tasks:
  # Ignoring errors because gunicorn could be down or not isntalled and it will fail as it should
  - name: Install python 
    apt:
      name: python3
      update_cache: yes
    sudo: True

  - name: Install python-venv
    apt:
      name: python3-venv
    sudo: True

  #TODO: Configure supervisor
  - name: Install supervisor
    apt:
      name: supervisor
    sudo: True

  - name: Install NginX
    apt: 
      name: nginx
    sudo: True 

  - name: Install git
    apt: 
      name: git
    sudo: True

  - name: Manually create the virtualenv with python
    command: python3 -m venv /home/ubuntu/venv

  - name: Install gunicorn
    pip:
      name: gunicorn
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5

  - name: Install pymysql
    pip: 
      name: pymysql
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5

  - name: Manually kill gunicorn processes with supervisor
    command: supervisorctl stop ytreviewsapi
    ignore_errors: yes
    sudo: True

  # - name: Manually stashing any local changes
  #   command: git stash
  #   args:
  #     chdir: /home/ubuntu/OneReview_Data_Collection

  # - name: Manually pull recent changes
  #   command: git pull
  #   args:
  #     chdir: /home/ubuntu/OneReview_Data_Collection

  # - name: Manually upgrade database
  #   command: /home/ubuntu/venv/bin/flask db upgrade
  #   args:
  #     chdir: /home/ubuntu/OneReview_Data_Collection/YTReviewsAPI

  - name: Creating deployment directory
    file:
      path: /home/ubuntu/deployment
      state: directory
      owner: ubuntu

  - name: Clearing deployment directory
    command: rm -rf *
    args:
      chdir: /home/ubuntu/deployment
    ignore_errors: yes

  - name: Installing application
    pip: 
      name: YTReviewsAPI
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5
      extra_args: --no-cache-dir
      chdir: /home/ubuntu/deployment 

  - name: Moving requirements.txt for application 
    copy: 
      src: requirements.txt
      dest: /home/ubuntu/deployment/requirements.txt


  - name: Install requirements
    pip: 
      name: /home/ubuntu/deployment/requirements.txt
      extra_args: -r
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5

  # - name: Copying static files
  #   copy:
  #     src: "{{ local_static_path }}"
  #     dest: /home/ubuntu/deployment/static
  #     directory_mode: True
  #     owner: ubuntu
  #     group: ubuntu
  #   sudo: True

  # - name: configuring system environment
  #   template:
  #     src: templates/config.j2
  #     dest: /home/ubuntu/OneReview_Data_Collection/YTReviewsAPI/config.py

  - name: Copying NginX Configuration
    template:
      src: templates/nginx.j2
      dest: /etc/nginx/sites-enabled/YTReviewsAPI
    sudo: True

  - name: Restart NginX
    service:
      name: nginx
      state: restarted
    sudo: True

  - name: Copying Supervisor configuration 
    template:
      src: templates/supervisor.j2
      dest: /etc/supervisor/conf.d/ytreviewsapi.conf
    sudo: True

  - name: Manually reload supervisor
    command: supervisorctl reload
    sudo: True

  # - name: Start application
  #   gunicorn:
  #     app: 'app'












