- hosts: all
  vars:
    http_port: 80
  remote_user: ubuntu
  # become: True
  vars_files:
    - vars.yml
  tasks:
  # Ignoring errors because gunicorn could be down or not isntalled and it will fail as it should
  - name: Install python 
    apt:
      name: python3
      update_cache: yes
    sudo: True

  - name: Install python-venv
    apt:
      name: python3-venv
    sudo: True

  #TODO: Configure supervisor
  - name: Install supervisor
    apt:
      name: supervisor
    sudo: True

  - name: Install NginX
    apt: 
      name: nginx
    sudo: True 

  - name: Install git
    apt: 
      name: git
    sudo: True

  - name: Manually create the virtualenv with python
    command: python3 -m venv /home/ubuntu/venv

  - name: Install gunicorn
    pip:
      name: gunicorn
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5

  - name: Install pymysql
    pip: 
      name: pymysql
      virtualenv: /home/ubuntu/venv
      virtualenv_python: python3.5




