"""addds password hash for admin

Revision ID: 3f5370a75f01
Revises: 5c413e3966aa
Create Date: 2019-06-18 18:23:13.214098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5370a75f01'
down_revision = '5c413e3966aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_hash')
    # ### end Alembic commands ###
