"""adds stats

Revision ID: 9557ba6f81f2
Revises: 4c24e391384f
Create Date: 2019-06-11 18:25:08.171081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9557ba6f81f2'
down_revision = '4c24e391384f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('commentCount', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('dislikeCount', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('favoriteCount', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('likeCount', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'views')
    op.drop_column('video', 'likeCount')
    op.drop_column('video', 'favoriteCount')
    op.drop_column('video', 'dislikeCount')
    op.drop_column('video', 'commentCount')
    # ### end Alembic commands ###
