"""adds a score attribute

Revision ID: bdfc8007ad92
Revises: 6c8049673b57
Create Date: 2019-08-01 07:59:25.840576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfc8007ad92'
down_revision = '6c8049673b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'score')
    # ### end Alembic commands ###
