"""init

Revision ID: e5665e26a852
Revises: 
Create Date: 2019-08-16 20:53:32.618834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5665e26a852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('logged_in', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admin_token'), 'admin', ['token'], unique=True)
    op.create_table('server__controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CURRENT_API', sa.Integer(), nullable=True),
    sa.Column('CURRENT_FILE_INDEX', sa.Integer(), nullable=True),
    sa.Column('CURRENT_MOVIE', sa.Integer(), nullable=True),
    sa.Column('CURRENT_VIDEO_ID', sa.Integer(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('mediaTitle', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likeCount', sa.Integer(), nullable=True),
    sa.Column('dislikeCount', sa.Integer(), nullable=True),
    sa.Column('favoriteCount', sa.Integer(), nullable=True),
    sa.Column('commentCount', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_title'), 'video', ['title'], unique=False)
    op.create_table('caption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('video_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('video_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('video_id', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description')
    op.drop_table('comment')
    op.drop_table('caption')
    op.drop_index(op.f('ix_video_title'), table_name='video')
    op.drop_table('video')
    op.drop_table('server__controller')
    op.drop_index(op.f('ix_admin_token'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
